version: '3.3'

services:
        app:
                container_name: searchservice_v1
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                ports:
                        - "44421:44421"
