server:
  port: 44421

spring:
  application:
    name: SearchService

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka